# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbxflow" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "06882fff7bf27c3cb63d0d2aace13c8d4868363d489226a3ce5f5b3a7f0c5a7e"
      url "https://github.com/jamessawle/sbxflow/releases/download/v#{version}/sbxflow_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d407b83b3f2dce9b99ca4148f8ad94a9eb51e439c8282be1e213ae7dc3f0929"
      url "https://github.com/jamessawle/sbxflow/releases/download/v#{version}/sbxflow_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "516ef912f751694ebee492494aee62aeaa39b30591b0a41e62a262b80ba23421"
      url "https://github.com/jamessawle/sbxflow/releases/download/v#{version}/sbxflow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad754b232ca6df1f3e0b1bffc206164dd4a7482315b292db467bdc1529247b29"
      url "https://github.com/jamessawle/sbxflow/releases/download/v#{version}/sbxflow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sbxflow"
  desc "Apply a repository's Docker Sandbox configuration and lifecycle"
  homepage "https://github.com/jamessawle/sbxflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbxflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sbxflow"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    sbxflow is not signed or notarized with an Apple Developer certificate.
    Installing it removes the macOS quarantine attribute from the executable
    so that Gatekeeper does not refuse to run it.
  EOS
end
