# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osch < Formula
  desc "CLI for managing OpenSpec schemas across repos"
  homepage "https://github.com/jamessawle/osch"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamessawle/osch/releases/download/v0.1.1/osch_0.1.1_darwin_amd64.tar.gz"
      sha256 "5eb713fe14ce2f92954148eadf93dfa192ec3e68bef705f25f0568ce4ecf1d11"

      define_method(:install) do
        bin.install "osch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamessawle/osch/releases/download/v0.1.1/osch_0.1.1_darwin_arm64.tar.gz"
      sha256 "cf61f1f3f2d710381f87a0d6095905dd20ca144bdfbd8e2f7651179a23d111ab"

      define_method(:install) do
        bin.install "osch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamessawle/osch/releases/download/v0.1.1/osch_0.1.1_linux_amd64.tar.gz"
      sha256 "1e9a68f4caad4ca46278ac5b46da04347738b1497cf9bf331d715a6a569d3bab"
      define_method(:install) do
        bin.install "osch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamessawle/osch/releases/download/v0.1.1/osch_0.1.1_linux_arm64.tar.gz"
      sha256 "32001ee87a470b350444faf60527822305606c989d1f5bf64626ef3a2ab855b2"
      define_method(:install) do
        bin.install "osch"
      end
    end
  end

  test do
    system bin/"osch", "version"
  end
end
