# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osch < Formula
  desc "CLI for managing OpenSpec schemas across repos"
  homepage "https://github.com/jamessawle/osch"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamessawle/osch/releases/download/v0.0.5/osch_0.0.5_darwin_amd64.tar.gz"
      sha256 "55e6525dccebfca307c898bca43d56bb5fecad9c657792fa2fa945edede00df0"

      define_method(:install) do
        bin.install "osch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamessawle/osch/releases/download/v0.0.5/osch_0.0.5_darwin_arm64.tar.gz"
      sha256 "a741068180aa9c67c26388761425fbeaead728e187241d2123cc8d7a2b836734"

      define_method(:install) do
        bin.install "osch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamessawle/osch/releases/download/v0.0.5/osch_0.0.5_linux_amd64.tar.gz"
      sha256 "5af81cc352a60c5d98a85255c28ff6dcfad71e57cac7409f65c1eb41c6c46aed"
      define_method(:install) do
        bin.install "osch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamessawle/osch/releases/download/v0.0.5/osch_0.0.5_linux_arm64.tar.gz"
      sha256 "4e8dd8a3a1bbcb7bc35495335227d894c1c3e1ee0c28d66bf67be8d89c11bbc1"
      define_method(:install) do
        bin.install "osch"
      end
    end
  end

  test do
    system "#{bin}/osch", "version"
  end
end
