# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbxflow < Formula
  desc "Apply a repository's Docker Sandbox configuration and lifecycle"
  homepage "https://github.com/jamessawle/sbxflow"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamessawle/sbxflow/releases/download/v0.1.3/sbxflow_0.1.3_darwin_amd64.tar.gz"
      sha256 "6231c0bc16427dd0e46e8eefa4a319af84123bbf9deb1fd0a14ea34ff320903b"

      define_method(:install) do
        bin.install "sbxflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamessawle/sbxflow/releases/download/v0.1.3/sbxflow_0.1.3_darwin_arm64.tar.gz"
      sha256 "257e4b3f0bd073a3a47b64a8fa50b4c7beeeaf84ca4f141e9854fa7c77339a96"

      define_method(:install) do
        bin.install "sbxflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamessawle/sbxflow/releases/download/v0.1.3/sbxflow_0.1.3_linux_amd64.tar.gz"
      sha256 "4d621084daabc23e010a9323beb944aa9495c374055d8bea072607edd56030c9"
      define_method(:install) do
        bin.install "sbxflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamessawle/sbxflow/releases/download/v0.1.3/sbxflow_0.1.3_linux_arm64.tar.gz"
      sha256 "115a90851d45c3e0c6d4ab4e1ea9c438d8baa11950ae1fb9e453f0fae91dc331"
      define_method(:install) do
        bin.install "sbxflow"
      end
    end
  end

  test do
    system bin/"sbxflow", "--version"
  end
end
